server.port=8081
spring.application.name=user-service

# =========================
# H2 DATABASE
# =========================
spring.datasource.url=jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =========================
# RABBITMQ
# =========================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# =========================
# RABBITMQ EXCHANGES
# =========================

# FANOUT EXCHANGE
rabbitmq.exchange.notifications=notifications.exchange

# DIRECT EXCHANGE
rabbitmq.exchange.payments=payments.exchange

# =========================
# QUEUES
# =========================

# CUSTOMER QUEUES
rabbitmq.queue.booking-confirmed-customer=booking.confirmed.customer
rabbitmq.queue.booking-rejected-customer=booking.rejected.customer

# ADMIN PAYMENT FAILURE QUEUE
rabbitmq.queue.payment-failed-admin=payment.failed.admin

# =========================
# ROUTING KEYS
# =========================

# DIRECT EXCHANGE ROUTING KEY
rabbitmq.routing.payment-failed=PaymentFailed